### ISSUE TITLE
artix openrc how to ?

### ISSUE THREAD

**Issue by jemadux** [jmesmon/illum#18]
I am using artix with openrc ... which line should i edit so i can use it for my system ?

**Comment by codyps** [comment]
Hi @jemadux . It's been a while since I used a system with openrc, so I'm not sure of current practice. https://github.com/jmesmon/illum/blob/master/illum.openrc was what seemed to work on gentoo for me back when I was running openrc on it, but even at the time I wasn't quite sure exactly how openrc wanted me to do things, so it might not be the best representation of how to do things.

I've taken a quick look at https://github.com/OpenRC/openrc/blob/master/service-script-guide.md which seems to document current practice, and using this openrc script may work for you:

```
#!/sbin/openrc-run
command="/usr/bin/illum-d"
command_background=true
output_logger=true
error_logger=true
```

This is untested, but based on the documentation I expect it to work. It would be very helpful to me if you tried it out and let me know if it worked or if there are improvements/fixes that need to be made.

If this is not quite what you're looking/asking for, or if some other clarification or information could be useful, please let me know. I'm happy to help here.

**Comment by jemadux** [comment]
hmm .. let's see .. on artix for linux-lts it is working fine .... 
but in linux and linux-zen it is not .. .
I don't know if in arch working ...
